<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tagme"
 *
 * Auto generated by Extension Builder 2014-02-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Tags',
	'description' => 'Tags  for social media, mainly for www.tumblr.com',
	'category' => 'plugin',
	'author' => 'Bingquan Bao',
	'author_email' => 'bingquan.bao@gmail.com',
	'author_company' => 'BBQ',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>